POST http://localhost:3000/api/hello
Content-Type: application/json

{
    "messengerURL": "hello"
}
########

POST http://localhost:3000/api/sender
Content-Type: application/json

{
    "messengerURL" : "https://www.messenger.com/t/100005543894347",
    "pass": "test",
    "total": 15
}

#######

POST http://localhost:3000/api/terminate
Content-Type: application/json

{
    "pass": "1ccd8730652e2783e6d8"
}